version: '2'
services:
    lcsampleapplication-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/LCSampleApplication/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=LCSampleApplication
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
